version: "3"
services:
  web:
    image: $ECR/myapp:0.02
    depends_on:
      - redis
    ports:
      - "80:80"
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /Users/yoava/tmp/redis_data:/data
    restart: always
