version: "2"
services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "80:5000"
  jenkins:
    image: jenkinsci/docker-workflow-demo
    container_name: jenkins_demo
    group_add:
      - $DOCKER_GROUP
    ports:
      - "8088:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
